### ISSUE TITLE
problem serving model

### ISSUE THREAD

**Issue by Cherchercher** [howl-anderson/rasa_contrib#8]
steps to reproduce:
1. rasa train nlu \
    --config ./configs/$agent/rasa_config.yml \
    --nlu ./core/$agent/training_data.json \
    --fixed-model-name core_$agent \
    --out ./models
    --verbose
2 . rasa run -v -m models --enable-api --port 5000

{"version":"1.5.3","status":"failure","message":"An unexpected error occurred. Error: (400, 'ParsingError', 'An unexpected error occurred. Error: SavedModel file does not exist at: \/tmp\/tmpoyzgq_93\/nlu\/addons_intent_classifier_textcnn_tf\/{saved_model.pbtxt|saved_model.pb}')","reason":"ParsingError","details":{},"help":null,"code":500}

**Comment by howl-anderson** [comment]
Thanks for your report, I will work on this issue very soon.

**Comment by howl-anderson** [comment]
If you are using rasa_contrib from Github master branch or PyPI. there is a bug inside, I fixed in develop branch a few weeks ago, but I don't release to master branch and PyPI. Sorry about that. Update rasa_contrib to latest version from PyPI should fix this bug.

**Comment by Cherchercher** [comment]
thanks for the update, that works
